#
# Sample PVT Configuration File.
#resources: ['jboss-brms-%{version}-engine.zip', 'jboss-brms-bpmsuite-%{version}-maven-repository.zip']
#

product: INTPACK
version: 1.7.0.redhat-630021
distrepo: http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/jboss-intpack/INTPACK-%{version}/
tests:
  org.jboss.pvt.generic.NoSignatureCheckTest:
    resources: ['fuse-integration-eap-distro-%{version}.zip','fuse-integration-eap-full-%{version}-installer.zip','fuse-integration-karaf-distro-%{version}.zip']
  org.jboss.pvt.generic.JDKCompatibleCheckTest:
    resources: ['fuse-integration-eap-distro-%{version}.zip','fuse-integration-eap-full-%{version}-installer.zip','fuse-integration-karaf-distro-%{version}.zip']
    filters: ['example.*']
    params: {min-version: '48', 'max-version':'52'}
  org.jboss.pvt.generic.VersionFormatTest:
    resources: ['fuse-integration-eap-distro-%{version}.zip','fuse-integration-eap-full-%{version}-installer.zip','fuse-integration-karaf-distro-%{version}.zip']
    filters: ['.*jboss-modules.jar.*', '.*/client/.*', '.*/bin/.*','.*/bundled/.*']
    params: {'format':'.*[\.-]redhat-\d+.*'}
