#
# Sample PVT Configuration File.
#

product: BPMS
version: 7.0.0.ER3
distrepo: http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/rhbas/BPMS-%{version}/
tests:
  org.jboss.pvt.generic.NoSignatureCheckTest:
    resources: ['rhbas-%{target}-kie-server-ee7.zip', 'rhbas-%{target}-business-central-eap7.zip', 'rhbas-%{target}-add-ons.zip']
    filters: ['.*bouncycastle/.*']
  org.jboss.pvt.generic.JDKCompatibleCheckTest:
    resources: ['rhbas-%{target}-kie-server-ee7.zip', 'rhbas-%{target}-business-central-eap7.zip', 'rhbas-%{target}-add-ons.zip']
    filters: ['.*example.*']
    params: {min-version: '48', 'max-version':'52'}
  org.jboss.pvt.generic.VersionFormatTest:
    resources: ['rhbas-%{target}-kie-server-ee7.zip', 'rhbas-%{target}-business-central-eap7.zip', 'rhbas-%{target}-add-ons.zip']
    filters: ['.*jboss-modules.jar.*', '.*/client/.*', '.*/bin/.*','.*/bundled/.*']
    params: {'format':'.*[\.-]redhat-\d+.*'}
