#
# Sample PVT Configuration File.
#

product: BRMS
version: 7.0.0.DR1
distrepo: http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/rhdm/BRMS-%{version}/
tests:
  org.jboss.pvt.generic.NoSignatureCheckTest:
    resources: ['rhdm-%{target}-kie-server-ee7.zip', 'rhdm-%{target}-decision-central-eap7.zip', 'rhdm-%{target}-add-ons.zip']
    filters: ['.*bouncycastle/.*']
  org.jboss.pvt.generic.JDKCompatibleCheckTest:
    resources: ['rhdm-%{target}-kie-server-ee7.zip', 'rhdm-%{target}-decision-central-eap7.zip', 'rhdm-%{target}-add-ons.zip']
    filters: ['.*example.*']
    params: {min-version: '48', 'max-version':'52'}
  org.jboss.pvt.generic.VersionFormatTest:
    resources: ['rhdm-%{target}-kie-server-ee7.zip', 'rhdm-%{target}-decision-central-eap7.zip', 'rhdm-%{target}-add-ons.zip']
    filters: ['.*jboss-modules.jar.*', '.*/client/.*', '.*/bin/.*','.*/bundled/.*']
    params: {'format':'.*[\.-]redhat-\d+.*'}
