---
### add cekit repos, binary and deps ###

- name: Copy cekit repos config
  copy:
    src: data/rhba-osbs/cekit/cekit.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Install packages
  yum:
    pkg: [ 'rhpkg', 'brewkoji', 'ca-certificates', 'authconfig', 'krb5-workstation',
           'odcs-client', 'python-krbV', 'source-to-image' ]
    state: latest

- name: Update all packages
  yum:
    name: "*"
    state: latest

### add download.sh script (this will download build-overrides.sh and build-osbs.sh from jboss-kie-modules) ###

- name: Create tools directory for rhba builds
  file:
    path: /opt/rhba
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins

- name: Copy the download.sh script to /opt/rhba
  copy:
    src: data/rhba-osbs/scripts/download.sh
    dest: /opt/rhba/
    owner: jenkins
    group: jenkins
    mode: 0744

### cekit config ###

- name: Create .cekit directory for jenkins user
  file:
    path: /home/jenkins/.cekit
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins


- name: Copy cekit config to jenkins user
  copy:
    src: data/rhba-osbs/cekit/config
    dest: /home/jenkins/.cekit/
    owner: jenkins
    group: jenkins


- name: install cekit and its deps using virtualenv
  pip:
    name: cekit==3.2.0, behave, lxml, docker-squash
    virtualenv: /home/jenkins/virtenvs/cekit

### krb5 config ###

- name: Copy krb5 config to /etc/krb5.conf
  copy:
    src: data/rhba-osbs/krb5/krb5.conf
    dest: /etc/

### ldap config ###

- name: Copy ldap config to /etc/openldap
  copy:
    src: data/rhba-osbs/ldap/ldap.conf
    dest: /etc/openldap/

### redhat root certs ###

- name: Download root certs
  get_url:
    url: "{{ item }}"
    dest: /etc/pki/ca-trust/source/anchors/
    validate_certs: no
  with_items:
    ['https://password.corp.redhat.com/legacy.crt', 'https://password.corp.redhat.com/RH-IT-Root-CA.crt']

- name: Create cacerts directory
  file:
    path: /etc/openldap/cacerts
    state: directory
    recurse: yes

- name: Copy legacy root certs to cacerts
  copy:
    src: /etc/pki/ca-trust/source/anchors/{{ item }}
    dest: /etc/openldap/cacerts/
    remote_src: yes
  with_items:
    [legacy.crt, RH-IT-Root-CA.crt]

- name: Rehash cacerts
  command: cacertdir_rehash /etc/openldap/cacerts

- name: Update ca trust
  command: update-ca-trust

- name: Make node.js use the system root CA
  copy:
    dest: /etc/profile.d/nodejscerts.sh
    mode: 0755
    content: |
      export NODE_EXTRA_CA_CERTS=/etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt


### ssh config ###

- name: Set no strict host checking
  shell: echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
...
